[package]
name = "prime_finder"
version = "3.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-integer = "0.1.44"
num_cpus = "1.0"
indicatif = "0.16.2"
